# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jamie Klube
title: Senior Network engineer
email: iceklube@gmail.com
website: iceklube.github.io

# Social links
twitter_username: iceklube
github_username:  iceklube
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: iceklube
linkedin_username: jamieklube
# pinterest_username: jekyll
youtube_username: not available
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jamie and I am network engineer moving into the Cloud with a focus on
  AWS.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: false
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
